version: "3.9"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - inner_net

  server:
    build: .
    ports:
      - "80:3000"
    networks:
      - inner_net
    depends_on:
      - redis
    restart: always

networks:
  inner_net:

