name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - deploy-server

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_EB_ENVIRONMENT_NAME: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
  APP_NAME: ${{ secrets.APP_NAME }}
  WORKING_DIRECTORY: './packages/server2'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: create docker env
        run: |
          rm -rf .env.docker
          echo "PORT=$PORT" >> .env.docker
          echo "DATABASE_URL=$DATABASE_URL" >> .env.docker
          echo "REDIS_HOST=$REDIS_HOST" >> .env.docker
          echo "REDIS_PORT=$REDIS_PORT" >> .env.docker
        env:
            PORT: ${{ secrets.PORT }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            REDIS_HOST: ${{ secrets.REDIS_HOST }}
            REDIS_PORT: ${{ secrets.REDIS_PORT }}
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Create ZIP archive of the repository
        run: zip -r ../../${{ env.APP_NAME }}.zip .
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APP_NAME }}
          environment_name: ${{ env.AWS_EB_ENVIRONMENT_NAME }}
          region: ${{ env.AWS_REGION }}
          version_label: ${{github.SHA}}
          deployment_package: ${{ env.APP_NAME }}.zip

