name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - prod-server

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_EB_ENVIRONMENT_NAME: ${{ secrets.AWS_EB_ENVIRONMENT_NAME }}
  APP_NAME: 'discord-backend'
  WORKING_DIRECTORY: './packages/server2'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Create ZIP archive of the repository
        run: zip -r ${{ env.APP_NAME }}.zip .
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        working-directory: ${{ env.WORKING_DIRECTORY }}
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APP_NAME }}
          environment_name: ${{ env.AWS_EB_ENVIRONMENT_NAME }}
          region: ${{ env.AWS_REGION }}
          version_label: ${{github.SHA}}
          deployment_package: ${{ env.APP_NAME }}.zip

