name: Example workflow for S3 Deploy
on:
  push:
    branches:
      - deploy-client

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      WORKING_DIRECTORY: './packages/client'

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: create env
        run: |
          rm -rf .env.production
          echo "VITE_SERVER_URL=$VITE_SERVER_URL" >> .env.production
        env:
          $VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: yarn build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: './packages/client/dist'
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
