name: Example workflow for S3 Deploy
on:
  push:
    branches:
      - prod-client

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      WORKING_DIRECTORY: './packages/client'

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build
        run: yarn build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: ${{ env.WORKING_DIRECTORY }}/dist
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
